### ISSUE TITLE
vector integration with display manager

### ISSUE THREAD

**Issue by theoden8** [stacompsoc/Heap-Project-1#5]
The program fails to run because the vectors are not properly integrated into display manager.

What I see should be done is:

physical object's x, y should be replaced with position vector;
display manager's x, y  -- .. -- with position vector.
change put_text and other functions to match the new data structure.

**Comment by mallok-s** [comment]
I don't understand what the issue is, the program seems to be running fine. Have you pushed the path to the repo? Or does the error occur after a certain amount of time?

**Comment by theoden8** [comment]
It occurs before the display initialises for some reason. This is the first exception I get every time I start fixing:

```
starting simulation
initializing model
2017-01-03 18:16:38.193 Python[49834:d07] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/l1/slb8b_7x13jctg8ch4gq39440000gq/T/org.python.python.savedState
tick
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    main()
  File "main.py", line 9, in main
    model.run()
  File "/Users/Admin/apps/_src/_MultiLanguage/Heap-Project-1/src/model.py", line 37, in run
    if not self.tick():
  File "/Users/Admin/apps/_src/_MultiLanguage/Heap-Project-1/src/model.py", line 45, in tick
    return self.display.tick()
  File "/Users/Admin/apps/_src/_MultiLanguage/Heap-Project-1/src/display_manager.py", line 220, in tick
    s.put_object(new_image, p, COLORS[color])
  File "/Users/Admin/apps/_src/_MultiLanguage/Heap-Project-1/src/display_manager.py", line 181, in put_object
    if not s.in_display(coords):
  File "/Users/Admin/apps/_src/_MultiLanguage/Heap-Project-1/src/display_manager.py", line 84, in in_display
    x, y = point
TypeError: 'NoneType' object is not iterable
```

This entails rewriting quite a lot of code, so I wanted to make sure it is not just my problem, because at the moment I have to use python2 (my python3.6 does not install pygame).

**Comment by theoden8** [comment]
Fixed by installing pygame for python3.
